### ISSUE TITLE
Claims missing under MvcHybridClient

### ISSUE THREAD

**Issue by David-Jacobsen** [damienbod/AspNetCoreWindowsAuth#7]
Hello,
If I uncomment out the lines 430 -> 433 under STS, AccountController.cs, then it adds all of the windows groups as claims.
Then I also uncommented out line 193 so that those claims get added as AdditionalLocalClaims.

Doing this, I can see all of the windows groups as claims if I put a break point in the Index method of the HomeController within the STS project after using windows authentication.

However, if I launch the MvcHybridClient and login through the identity server using windows authenticaiton, then when it redirects me to the Index method of the HomeController within the MvcHybridClient project, I do not see any of the windows groups as claims.

Can you point me in the right direction?

**Comment by damienbod** [comment]
Hi David

I added fixes for this. s extra things were required, the IProfileService and also included the claims in the id_token

See the pull request.

https://github.com/damienbod/AspNetCoreWindowsAuth/pull/8

Will merge this soon, just want to do further testing

Thanks for reporting.

**Comment by damienbod** [comment]
There is different ways of mapping the claims, you can chose this yourself, I will leave the claims in the id_token for this demo

https://damienbod.com/2019/11/01/user-claims-in-asp-net-core-using-openid-connect-authentication/

greeitngs Damien

**Comment by damienbod** [comment]
merged now, all work, I only added the role claims, maybe you want some of the other ones This can be done in the profile service
