### ISSUE TITLE
Manual missing

### ISSUE THREAD

**Issue by kkrzysiek** [damienbod/AspNetCoreWindowsAuth#9]
Would be nice to know how to run this project. I can see 3 projects, API, Web, Web. 
When started the API and did some basic requests, there were errors. The websites also did not start at all. How to run it? :)

**Comment by damienbod** [comment]
Start the StsServer project, the Web API project and the MvcHybrid project and all should run.
 
I will update this to .NET 5 and add a better get started readme

thanks for reporting

Greetings Damien

**Comment by damienbod** [comment]
Updated and added a small startup manual

https://github.com/damienbod/AspNetCoreWindowsAuth#running-the-applications

Greetings Damien

**Comment by kkrzysiek** [comment]
Perfect :) thanks :) 
Do you have anything about using smartcards for user authentication to windows active directory or azure active directory? currently i'm facing such issue.

**Comment by damienbod** [comment]
Hi @kkrzysiek You could use FIDO2 with Azure Active directory, this is the best way to secure your users.
